steps: 
  - name: node:alpine
    entrypoint: npm
    args: ["install"]
  - name: node:alpine
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - 'PORT=$_PORT'
      - 'DB_USER=$_DB_USER'
      - 'DB_PASSWORD=$_DB_PASSWORD'
      - 'DB_ADDRESS=$_DB_ADDRESS'
      - 'DB_PORT=$_DB_PORT'
      - 'DB_NAME=$_DB_NAME'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$TRIGGER_NAME', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$TRIGGER_NAME']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      [
        'beta', 
        'run', 
        'deploy', 
        '$TRIGGER_NAME', 
        '--image', 
        'gcr.io/$PROJECT_ID/$TRIGGER_NAME', 
        '--region',
        'asia-east1',
        '--platform', 
        'managed', 
        '--quiet']
images:
  - gcr.io/$PROJECT_ID/$TRIGGER_NAME